# FOR DEVELOPMENT & TESTING
server.port=8000

# Database Configuration
# -------------------------
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Logging Settings
# -------------------------
logging.level.root=${SPRING_SECURITY_LOG_LEVEL:INFO}
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

# Path Settings
# -------------------------
# Base directory for the application
app.base-dir=${user.dir}

# Paths of binaries
path.bin-path=${app.base-dir}/bin

# Ytdlp binary path
path.ytdlp-bin=${path.bin-path}/youtube

# Download storage path
path.download-path=${app.base-dir}/storage/private/downloads

# Download Threads Settings
# -------------------------
# Threads to handle concurrent download requests
downloads.pool.core=4
downloads.pool.max=8
downloads.queue.capacity=50

# The amount of time it takes for a resource to expire
resource.expiry.time=2m

# Ytdlp Settings
# -------------------------
# Automatically update ytdlp binary
ytdlp.auto-update=false

# Use browser cookies for downloads
ytdlp.use-cookies=true

# Specify which browser to extract cookies from
ytdlp.browser-cookies=firefox
ytdlp.cookies-path=

# JavaScript runtime to use (needed if downloading from premium account)
ytdlp.js-runtime=node

# Download Settings
# -------------------------
# Kill download if it exceeds the time limit
download.timeout=5m

# Progress increment percentage to log
download.progress-increment=2