# Application Settings
# -------------------------
spring.application.name=ytdlp
server.address=0.0.0.0
api-version=v1
server.servlet.context-path=/api/${api-version}

# Database Configuration
# -------------------------
spring.datasource.url=${DOWNLOADER_DB_URL:postgresql}
spring.datasource.username=${DOWNLOADER_DB_USERNAME:postgres}
spring.datasource.password=${DOWNLOADER_DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver