# Application Settings
# -------------------------
spring.application.name=ytdlp
server.address=0.0.0.0
api-version=v1
server.servlet.context-path=/api/${api-version}

# Database Configuration
# -------------------------
spring.datasource.url=jdbc:postgresql://localhost:5050/downloader
spring.datasource.username=scrappyz
spring.datasource.password=gagoka30
spring.datasource.driver-class-name=org.postgresql.Driver